/* =====================================================================
   ACS REVISION — content data
   ---------------------------------------------------------------------
   Single source of truth for the reference library, flashcards, quizzes
   AND the grounding context handed to the AI tutor (see api/ask.js).

   Covers: CCN1 (core domestic gas safety) + CENWAT, CKR1, HTR1, MET1.

   IMPORTANT — this is a revision aid drafted from UK gas regulations and
   British Standards. Figures and procedures must always be verified
   against the CURRENT editions of the official documents (GSIUR 1998,
   the relevant BS / IGEM standards, manufacturer instructions and your
   accredited training centre's materials) before relying on them in the
   field. Standards change; this content is a memory jogger, not the law.
   ===================================================================== */

window.ACS = (function () {
  // ---- Categories ----------------------------------------------------
  const categories = [
    { id: "ccn1",   name: "CCN1",   full: "Core Domestic Gas Safety",            color: "#c99c38" },
    { id: "cenwat", name: "CENWAT", full: "Central Heating Boilers & Water Heaters", color: "#4f9dde" },
    { id: "ckr1",   name: "CKR1",   full: "Domestic Cookers",                    color: "#e08a4f" },
    { id: "htr1",   name: "HTR1",   full: "Gas Fires & Space Heaters",           color: "#cf5f7a" },
    { id: "met1",   name: "MET1",   full: "Domestic Metering",                   color: "#6bbf6b" },
  ];

  // ---- Reference topics ---------------------------------------------
  // Each: { id, cat, title, summary, points:[], refs:[], watch }
  const topics = [
    // ===================== CCN1 ======================================
    {
      id: "legislation",
      cat: "ccn1",
      title: "Legislation, competence & responsibilities",
      summary:
        "The legal framework every gas operative works under, and who is responsible for what.",
      points: [
        "Gas Safety (Installation and Use) Regulations 1998 (GSIUR) is the principal law for gas work in domestic and commercial premises.",
        "It is a criminal offence to carry out gas work unless you are competent (ACS-assessed) and on the Gas Safe Register — the register replaced CORGI on 1 April 2009.",
        "The Health and Safety at Work etc. Act 1974 is the overarching duty of care; HSE is the enforcing authority for gas safety.",
        "Gas Safe ID card shows the categories of work you are qualified for on the reverse — only work within those categories.",
        "Landlords must arrange an annual Gas Safety check (Landlord Gas Safety Record, 'CP12') on each appliance/flue and keep records (GSIUR reg 36).",
        "Manufacturer's installation/servicing instructions take priority for the specific appliance and must be left with the customer.",
      ],
      refs: ["GSIUR 1998 (esp. regs 3, 26, 36)", "HSW Act 1974", "Gas Safe Register"],
      watch: "Never work outside the categories on your ID card. Working while not registered/competent is a criminal offence, not just bad practice.",
    },
    {
      id: "emergencies",
      cat: "ccn1",
      title: "Gas escapes & emergencies",
      summary: "What to do when you smell gas or find an escape, and the actions in the right order.",
      points: [
        "National Gas Emergency Service: 0800 111 999 (free, 24h). Report any uncontrolled escape immediately.",
        "On smelling gas: turn off the Emergency Control Valve (ECV), do NOT operate electrical switches, extinguish naked flames, open doors/windows to ventilate.",
        "The gas supplier/transporter must attend within set timescales (generally 1 hour for an uncontrolled escape, 2 hours for a controlled escape) under GSMR.",
        "If you cannot make the situation safe, isolate, warn the responsible person, label, and report — never leave a known dangerous situation live.",
        "Carbon monoxide is a separate emergency: get people out into fresh air, seek medical help, and treat the appliance as Immediately Dangerous.",
      ],
      refs: ["GSIUR 1998 reg 37", "Gas Safety (Management) Regulations (GSMR)", "GIUSP"],
      watch: "Do not turn electrical switches on or off in a gas-filled space — a spark can ignite the escape.",
    },
    {
      id: "giusp",
      cat: "ccn1",
      title: "Unsafe situations (GIUSP): ID, AR & NCS",
      summary:
        "The Gas Industry Unsafe Situations Procedure (now IGEM/G/11) — how to classify and act on a dangerous appliance.",
      points: [
        "GIUSP is published as IGEM/G/11 — current is Edition 2 (with amendments July 2022, June 2024 and July 2025). It classifies unsafe situations into just TWO categories: Immediately Dangerous (ID) and At Risk (AR).",
        "Principal objective on finding an unsafe situation: make safe, and advise the responsible person not to use the appliance/installation — explaining it's in the interest of gas safety.",
        "Immediately Dangerous (ID): an immediate danger to life or property if left connected. Typically failed tightness or spillage tests, or serious flue / ventilation / combustion deficiencies (e.g. products of combustion entering the room, gas escapes).",
        "At Risk (AR): one or more faults that may in the future be a danger to life or property (e.g. inadequate ventilation). Generally turn off with the responsible person's permission and attach a 'DANGER — DO NOT USE' label.",
        "Exception: a few situations aren't made safer by turning off (e.g. building work over a PE gas service pipe, or an incorrectly sited LPG bulk vessel) — these are referred to a responsible person/organisation and do NOT get a 'DANGER — DO NOT USE' label.",
        "Always get the responsible person's permission to turn off/disconnect, and inform them of the reasons.",
        "Leave a Warning Notice stating the category (ID or AR), what's unsafe, actions taken, what's needed to rectify, any RIDDOR report, the engineer/company details and emergency contacts (Appendix 6).",
        "Some ID situations meet RIDDOR criteria and must be reported; keep records (advisable for at least 6 years).",
      ],
      refs: ["IGEM/G/11 Edition 2 (GIUSP, amdts to July 2025)", "RIDDOR", "GSIUR 1998"],
      watch: "Current IGEM/G/11 Edition 2 has only TWO unsafe categories — ID and AR. 'Not to Current Standards' (NCS) is NOT a GIUSP unsafe classification: it may be recorded/advised but must never go on an unsafe-situations Warning Notice. Many ACS centres still teach ID/AR/NCS for the exam, so learn all three — but know the current position.",
      source: { label: "IGEM/G/11 Edition 2 (the official standard, IGEM)", url: "https://www.igem.org.uk/resource/igem-g-11-edition-2-gas-industry-unsafe-situations-procedure.html" },
    },
    {
      id: "tightness",
      cat: "ccn1",
      title: "Tightness testing & purging",
      summary: "Proving an installation is gas-tight before and after work, and purging air/gas safely.",
      points: [
        "Domestic tightness testing & direct purging follow IGEM/UP/1B. The current edition is Edition 4 — mandatory from 1 October 2026 (Edition 3 is withdrawn on 30 September 2026).",
        "Edition 4's key change: the permissible pressure drop is now set by the Installation Volume (IV) — the actual internal gas volume of the section being tested, in m³ — NOT by the meter's badged size.",
        "IGEM/UP/1B covers small installations up to IV 0.035 m³; above that, IGE/UP/1 applies.",
        "Sequence: connect a gauge at a suitable test point, carry out a let-by test on the ECV, allow a stabilisation period, then the timed tightness test.",
        "Let-by test checks the ECV is not passing gas; the gauge should not rise during the let-by period.",
        "New installation pipework (no appliances, no meter): NO pressure drop is permitted over the test period.",
        "With appliances connected, a permitted drop applies based on the Installation Volume — read it from the IGEM/UP/1B Edition 4 tables/calculator.",
        "New in Edition 4: when appliances are connected, a pipework-only retest is a mandatory follow-on step — any perceptible movement on that retest is a fail.",
        "Always purge air (after install) or gas (before work) to a safe place, and re-test for tightness after reconnection.",
      ],
      refs: ["IGEM/UP/1B Edition 4", "IGE/UP/1 (larger installs)", "IGEM/UP/1A"],
      watch: "From 1 October 2026 only IGEM/UP/1B Edition 4 may be used: permissible drop is by Installation Volume (m³), not meter size, and the pipework-only retest (with appliances connected) is mandatory. Read the actual permitted drop from the current Edition 4 tables/calculator — don't rely on remembered figures.",
      source: { label: "IGEM/UP/1B Edition 4 (official, IGEM)", url: "https://www.igem.org.uk/resource/igem-up-1b-edition-4-tightness-testing-and-direct-purging-of-small-liquefied-petroleum-gas-air-ng-and-lpg-installations.html" },
    },
    {
      id: "pipework",
      cat: "ccn1",
      title: "Installation pipework",
      summary: "Materials, sizing, support, protection and the 1 mbar pressure-drop rule.",
      points: [
        "Domestic installation pipework up to 35 mm is covered by BS 6891.",
        "The maximum permitted pressure drop from the meter outlet to any appliance is 1 mbar for natural gas.",
        "Pipe must be adequately supported, protected from corrosion, and sleeved where it passes through walls/floors; sleeves must be sealed at the building-side end.",
        "Pipework in voids must be ventilated or the void monitored; gas pipes should not be run in unventilated cavities of external walls.",
        "Protect pipe from accidental damage and keep it clear of electrical cables (separation/sleeving where they must cross).",
        "Equipotential bonding (10 mm² minimum) is required to the installation pipework near the meter where electrical bonding applies.",
      ],
      refs: ["BS 6891", "BS 7671 (bonding)", "GSIUR 1998"],
      watch: "The 1 mbar drop is across the WHOLE installation pipework from the meter, not per appliance. Undersized pipe is a common cause of fail.",
    },
    {
      id: "pressure-gasrate",
      cat: "ccn1",
      title: "Operating pressure & gas rate",
      summary: "Checking the appliance gets the correct pressure and burns the correct amount of gas.",
      points: [
        "Natural gas nominal appliance operating (working) pressure is 20 mbar; check against the appliance data badge and manufacturer instructions.",
        "Standing (no-flow) pressure is typically a little higher (around 21–23 mbar) and should not be confused with working pressure.",
        "Gas rate (heat input) is measured at the meter and compared to the appliance data badge — a high rate can mean over-gassing, a low rate under-gassing.",
        "Metric meter method: time the gas used for a known volume, then gas rate (m³/h) = (3600 ÷ time in seconds) × volume in m³.",
        "Convert to heat input: kW (gross) ≈ gas rate (m³/h) × calorific value (MJ/m³) ÷ 3.6. Natural gas CV is roughly 38–39 MJ/m³ — use the value printed on the gas bill.",
        "Imperial meter: kW ≈ (ft³/h) × CV in Btu/ft³ ÷ 3412 (natural gas CV ≈ 1040 Btu/ft³).",
        "All other appliances should be off (and the pilot accounted for) while you take a gas-rate reading.",
      ],
      refs: ["Appliance data badge", "Manufacturer instructions", "Local CV on the gas bill"],
      watch: "Use the calorific value from the actual gas bill, not a textbook number — CV varies and using the wrong one gives a wrong kW.",
    },
    {
      id: "combustion",
      cat: "ccn1",
      title: "Combustion & flue gas analysis",
      summary: "What good combustion looks like and how the CO/CO₂ ratio is used.",
      points: [
        "Complete combustion of natural gas produces carbon dioxide (CO₂) and water vapour; incomplete combustion produces carbon monoxide (CO) — colourless, odourless, toxic.",
        "A flue gas analyser (FGA) measures CO and CO₂ and calculates the CO/CO₂ ratio.",
        "The accepted maximum CO/CO₂ ratio for a correctly operating appliance is 0.004; above this the appliance fails on combustion.",
        "Causes of high CO: blocked/restricted flue, lack of ventilation/air, incorrect gas pressure, dirty/damaged burner or heat exchanger.",
        "Always zero/calibrate the analyser in fresh air and follow the manufacturer's test procedure and probe position.",
        "Combustion analysis is required by many manufacturers at service/commissioning (record on the Benchmark log).",
      ],
      refs: ["BS 7967 (FGA use)", "Manufacturer instructions", "Benchmark scheme"],
      watch: "A CO/CO₂ ratio above 0.004 is a combustion failure — investigate ventilation, flue and gas rate; don't just leave it running.",
    },
    {
      id: "ventilation",
      cat: "ccn1",
      title: "Ventilation for combustion air",
      summary: "Making sure an appliance has enough air to burn safely.",
      points: [
        "Ventilation requirements for domestic gas appliances are in BS 5440-2.",
        "Open-flued appliances draw combustion air from the room and need permanent purpose-provided ventilation when input is high enough.",
        "Rule of thumb for an open-flued appliance: a free air vent of 5 cm² per kW of net input rating ABOVE 7 kW (i.e. the first 7 kW needs no extra vent).",
        "Room-sealed (balanced/fan-flued) appliances take air from outside and do not normally need a room air vent.",
        "Flueless appliances (e.g. cookers, flueless heaters) need both room volume and ventilation considered, plus an openable window/door.",
        "Air vents must not be blocked or sleeved in a way that reduces free area; check the effective free area, not the overall size.",
      ],
      refs: ["BS 5440-2", "Manufacturer instructions"],
      watch: "It's the NET input above 7 kW for open-flued — and it's FREE area, not the grille's outside dimensions. Verify the appliance type first (room-sealed needs no vent).",
    },
    {
      id: "flues",
      cat: "ccn1",
      title: "Flues, chimneys & terminals",
      summary: "Flue types, the tests that prove a flue works, and terminal positioning.",
      points: [
        "Flueing of domestic gas appliances is covered by BS 5440-1; terminal positions and clearances are specified there.",
        "Flue types: open-flued (draws room air, products up a flue), room-sealed (balanced or fan-assisted), and flueless.",
        "Flue flow test (smoke) proves the flue is clear and pulling; carry it out before the spillage test on open-flued appliances.",
        "Spillage test confirms products of combustion are being removed and not spilling into the room — done with the appliance running, after closing doors/windows and with extract fans on.",
        "Terminals must be positioned away from openings, corners and obstructions by the minimum clearances in BS 5440-1 (e.g. clearances below openable windows, from corners, and above ground/balcony level).",
        "Plume management and proximity to boundaries/adjacent surfaces must follow the manufacturer and BS 5440-1.",
      ],
      refs: ["BS 5440-1", "Manufacturer instructions"],
      watch: "Specific terminal clearance distances change between editions — always read the current BS 5440-1 table rather than memorising old figures.",
    },
    {
      id: "co-safety",
      cat: "ccn1",
      title: "Carbon monoxide & CO alarms",
      summary: "Recognising CO risk, symptoms, and alarm requirements.",
      points: [
        "Carbon monoxide (CO) is produced by incomplete combustion — colourless, odourless and tasteless, so it cannot be detected by the senses.",
        "Early symptoms mimic flu: headache, dizziness, nausea, tiredness, breathlessness — but no temperature; symptoms ease when away from the property.",
        "Sources/causes: blocked flues, lack of ventilation, badly adjusted or faulty appliances, and using flueless appliances incorrectly.",
        "CO alarms must conform to BS EN 50291; siting guidance is in BS EN 50292 (and manufacturer instructions).",
        "A CO alarm is an additional safeguard, not a substitute for correct installation, servicing and ventilation.",
        "If CO is suspected: ventilate, get occupants out into fresh air, turn the appliance off, seek medical advice, and treat as Immediately Dangerous.",
      ],
      refs: ["BS EN 50291 (alarms)", "BS EN 50292 (siting)", "GIUSP"],
      watch: "Don't rely on a CO alarm to make a bad install safe — the alarm is a last line of defence, not a fix.",
    },
    {
      id: "electrical",
      cat: "ccn1",
      title: "Basic electrical safety checks",
      summary: "The electrical checks a gas operative must be able to carry out on gas appliances.",
      points: [
        "Gas operatives must be competent to carry out basic electrical safety checks on the appliances they work on (earth continuity, polarity, short circuit, resistance to earth).",
        "Earth continuity ensures exposed metalwork is connected to earth so a fault disconnects the supply.",
        "Polarity check confirms live and neutral are not reversed — reversed polarity is a fault to rectify.",
        "Main equipotential bonding (10 mm² minimum) connects gas (and water) installation pipework to the main earthing terminal — required where applicable.",
        "If electrical faults are outside your competence/scope, isolate where dangerous and refer to a qualified electrician.",
      ],
      refs: ["BS 7671 (IET Wiring Regs)", "GSIUR 1998"],
      watch: "Bonding clamps must be on the customer's side within 600 mm of the meter (and before any branch/tee/union) — a missing or wrongly placed bond is a common defect.",
    },

    // ===================== CENWAT ====================================
    {
      id: "boiler-types",
      cat: "cenwat",
      title: "Boiler types & condensing operation",
      summary: "Combi, system and regular boilers, and why modern boilers are condensing.",
      points: [
        "Combi (combination) boiler: instantaneous hot water and heating from one unit, no hot water cylinder or cold storage tank needed.",
        "System boiler: works with an unvented or vented hot water cylinder; most components (pump, expansion vessel) are built in.",
        "Regular/heat-only boiler: traditional open-vented system with a feed & expansion cistern and hot water cylinder.",
        "Condensing boilers recover latent heat from flue gases by condensing water vapour, achieving high efficiency (ErP A-rated, ~90%+).",
        "Condensing boilers produce acidic condensate that must be safely drained (see condensate disposal).",
        "Since 2005 (England & Wales) virtually all new domestic gas boilers must be condensing.",
      ],
      refs: ["ErP / Boiler efficiency (SEDBUK/ErP)", "Building Regs Part L", "Manufacturer instructions"],
      watch: "Match the boiler type to the system — fitting a combi where high simultaneous hot-water demand exists leads to poor performance complaints.",
    },
    {
      id: "sealed-systems",
      cat: "cenwat",
      title: "Sealed central heating systems",
      summary: "Expansion vessels, pressure relief and filling — the safety devices on a sealed system.",
      points: [
        "A sealed system is pressurised and uses an expansion vessel to absorb the expansion of water as it heats.",
        "The expansion vessel has a pre-charge (typically around 1 bar / matched to system static head) on the air side of the diaphragm.",
        "A pressure relief (safety) valve, usually set to 3 bar, discharges to a safe, visible point outside if pressure becomes excessive.",
        "Typical cold fill pressure is around 1–1.5 bar; pressure rises as the system heats.",
        "A filling loop (temporary or with a double-check valve) is used to top up the system and must be disconnected/isolated after use to prevent backflow.",
        "Loss of pressure points to a leak, a failed expansion vessel charge, or a passing/weeping PRV.",
      ],
      refs: ["Manufacturer instructions", "BS EN 12828", "Building Regs"],
      watch: "Check the expansion vessel charge with the system drained/depressurised — a flat vessel causes pressure to swing and the PRV to weep.",
    },
    {
      id: "heating-controls",
      cat: "cenwat",
      title: "Heating controls & Boiler Plus",
      summary: "Time and temperature control and the England 'Boiler Plus' requirements.",
      points: [
        "Basic controls: programmer/timer, room thermostat, cylinder thermostat (stored hot water) and thermostatic radiator valves (TRVs).",
        "Boiler Plus (England, from April 2018): all gas boiler installations must have time and temperature control.",
        "For combi boilers, Boiler Plus requires ONE additional energy-saving measure: flue gas heat recovery, weather compensation, load compensation, or a smart thermostat with automation & optimisation.",
        "Minimum gas boiler efficiency under Boiler Plus is ErP 92%.",
        "TRVs control individual radiator temperature; don't fit a TRV in the same room as the main room thermostat unless designed to work together.",
        "Correct controls improve efficiency and comfort and are a Building Regulations requirement.",
      ],
      refs: ["Boiler Plus (England, 2018)", "Building Regs Part L", "Manufacturer instructions"],
      watch: "Boiler Plus is an England requirement — Scotland, Wales and NI have their own building standards. Confirm what applies in the property's location.",
    },
    {
      id: "unvented-hw",
      cat: "cenwat",
      title: "Hot water & unvented cylinders (G3)",
      summary: "Stored hot water safety and why unvented work needs a separate qualification.",
      points: [
        "Unvented hot water storage systems are fed directly from the mains and store water under pressure — they require a separate competence (e.g. the G3/unvented qualification).",
        "Safety devices include an expansion vessel, an expansion/pressure relief valve, and a temperature & pressure relief valve discharging through a tundish to a safe point.",
        "Temperature relief typically operates around 90–95 °C to prevent the stored water reaching boiling.",
        "Stored hot water should be held at 60 °C and delivered hot enough to control Legionella (distribution generally ≥ 50 °C), balancing scald risk.",
        "Unvented installation/commissioning is notifiable under Building Regulations (Part G).",
        "A vented (open) cylinder uses a feed & expansion / cold water storage cistern and a vent pipe instead.",
      ],
      refs: ["Building Regs Part G (G3)", "BS EN 12897", "Manufacturer instructions"],
      watch: "You must hold the unvented (G3) qualification to install/commission unvented cylinders — it is NOT covered by CENWAT alone.",
    },
    {
      id: "condensate",
      cat: "cenwat",
      title: "Condensate disposal",
      summary: "Safely getting acidic condensate away from a condensing boiler.",
      points: [
        "Condensing boilers produce mildly acidic condensate that must be drained away safely and legally.",
        "Preferred routes are internal connection to a soil stack, internal waste/drain, or a kitchen/bathroom waste — kept internal and insulated where possible to avoid freezing.",
        "External condensate pipes should be minimised, kept as large as practicable (often 32 mm+), insulated, and run to a suitable termination to prevent freezing.",
        "A frozen condensate pipe is a common winter cause of boiler lockout — design it out where possible.",
        "Where a gravity route isn't available, a condensate pump can lift the discharge to a suitable drain.",
        "Follow the manufacturer's instructions and current guidance for pipe size, fall and termination.",
      ],
      refs: ["Manufacturer instructions", "BS 6798", "Building Regs Part H (drainage)"],
      watch: "External condensate runs freeze — insulate, upsize and keep them short. A frozen pipe is the classic 'no heat in a cold snap' callout.",
    },

    // ===================== CKR1 ======================================
    {
      id: "cooker-install",
      cat: "ckr1",
      title: "Cooker installation & stability",
      summary: "Connecting and securing domestic gas cookers safely.",
      points: [
        "Freestanding cookers must be installed with a stability device (chain/bracket) so the appliance cannot tip if weight is applied to an open door — installation per BS 6172.",
        "Flexible connection hoses for domestic cookers must comply with BS 669-1 and be the correct length/orientation, free from kinks, heat and sharp edges.",
        "Maintain the manufacturer's clearances from combustible surfaces, especially at the sides above hotplate level.",
        "The connection point and hose must remain accessible for inspection and isolation.",
        "Check the cooker is level and stable, hotplate burners cross-light correctly, and the oven/grill ignite and run safely.",
        "A flueless cooker relies on room ventilation and an openable window/door — confirm the room meets the ventilation requirements.",
      ],
      refs: ["BS 6172 (installation)", "BS 669-1 (flexible hose)", "Manufacturer instructions"],
      watch: "No stability bracket/chain on a freestanding cooker is a recognised unsafe situation — a loaded open oven door can tip an unsecured cooker.",
    },
    {
      id: "cooker-ventilation",
      cat: "ckr1",
      title: "Cooker ventilation (flueless)",
      summary: "Room volume and ventilation requirements for a flueless cooker.",
      points: [
        "A domestic cooker is a flueless appliance — its products of combustion enter the room, so ventilation matters.",
        "BS 5440-2 sets the room ventilation requirements based on room volume and whether there's an openable window/door.",
        "Commonly cited figures: room volume below 5 m³ needs a permanent vent (about 100 cm²); 5–10 m³ needs about 50 cm²; over 10 m³ generally needs no permanent vent if there's an openable window.",
        "An openable window or door direct to outside air is normally required regardless of room size.",
        "Where an extract fan or cooker hood is fitted, check it does not adversely affect any other open-flued appliance in the property (spillage risk).",
        "Always confirm the exact figures against the current BS 5440-2 — they vary by appliance and edition.",
      ],
      refs: ["BS 5440-2", "Manufacturer instructions"],
      watch: "Those cm²/volume figures are commonly quoted but DO verify against current BS 5440-2 — and remember an extract fan can pull an open-flued appliance into spillage.",
    },

    // ===================== HTR1 ======================================
    {
      id: "fire-types",
      cat: "htr1",
      title: "Gas fire & heater types",
      summary: "Open-flued, room-sealed, flueless and decorative fuel-effect fires.",
      points: [
        "Radiant/convector gas fires are commonly open-flued and sit in or in front of a builder's opening or fireplace.",
        "Decorative Fuel Effect (DFE) fires are open-flued, give a 'real fire' look and typically need a larger flue/chimney and good draught.",
        "Inset Live Fuel Effect (ILFE) fires are higher efficiency than DFE and have specific catchment/closure requirements.",
        "Room-sealed gas fires (e.g. balanced/glass-fronted) take combustion air from outside and are higher efficiency.",
        "Flueless gas fires include a catalytic converter/oxygen-depletion sensor and rely on room volume and ventilation.",
        "Always match the fire type to the flue/chimney available and the manufacturer's requirements.",
      ],
      refs: ["BS 5871 (installation)", "BS 5440-1", "Manufacturer instructions"],
      watch: "DFE fires need a proper Class 1 / suitable chimney and good draught — fitting one to an inadequate flue causes spillage and CO risk.",
    },
    {
      id: "fire-install",
      cat: "htr1",
      title: "Fire installation: hearths, closure plates & catchment",
      summary: "The fabric checks that make a gas fire installation safe.",
      points: [
        "Check the chimney/flue is the correct type and condition for the fire, and carry out flue flow and spillage tests before leaving.",
        "A correctly sized and sealed closure plate (debris/register plate) is required for many open-flued fires installed in a builder's opening.",
        "A catchment space (debris collection space) must be provided below the flue connection where required, to collect any debris falling from the chimney.",
        "Hearths must meet size and non-combustibility requirements to protect the floor in front of and beneath the fire.",
        "Maintain manufacturer's clearances to combustible shelves, surrounds and decorations above and beside the fire.",
        "Spillage test on a real fuel-effect/open-flued fire confirms products clear the room under worst-case conditions (doors/windows shut, fans on).",
      ],
      refs: ["BS 5871", "BS 5440-1", "Manufacturer instructions"],
      watch: "Missing closure plate or catchment space, wrong hearth, and a failed spillage test are classic HTR1 unsafe situations.",
    },
    {
      id: "flueless-heater",
      cat: "htr1",
      title: "Flueless space heaters",
      summary: "Room volume, ventilation and limits for flueless heaters.",
      points: [
        "Flueless space heaters discharge all products of combustion into the room, so room volume and ventilation are critical.",
        "They incorporate an atmosphere-sensing device / oxygen-depletion safety device that shuts the heater off if vitiation occurs.",
        "Minimum room volume and permanent ventilation requirements come from BS 5440-2 and the manufacturer — a minimum room size and a permanent air vent are normally specified.",
        "Flueless heaters must not be installed in certain rooms (e.g. bathrooms or bedrooms below a stated size) — check the appliance instructions and standards.",
        "There are limits on heat input for flueless heaters in a given space.",
        "Confirm an openable window or door to outside air is present.",
      ],
      refs: ["BS 5440-2", "BS 5871", "Manufacturer instructions"],
      watch: "Flueless heaters have strict room-type and room-size limits — putting one in too small a room, a bathroom or a bedroom can be an unsafe install.",
    },

    // ===================== MET1 ======================================
    {
      id: "meter-install",
      cat: "met1",
      title: "Meter installation & the emergency control",
      summary: "Where the gas comes in, how it's controlled and metered.",
      points: [
        "The Emergency Control Valve (ECV) is the consumer's main means of shutting off the gas; it must be accessible with a handle that's clearly identifiable (and shows on/off).",
        "A gas emergency notice should be displayed at or near the meter/ECV telling the user what to do if they smell gas (and the 0800 111 999 number).",
        "Domestic diaphragm meters (e.g. U6 / G4) measure volume; modern installs may have smart meters.",
        "A meter regulator (governor) reduces incoming pressure to the nominal supply pressure for the installation.",
        "The meter installation must be correctly supported, electrically bonded where required, and protected from damage/weather (meter boxes for external meters).",
        "There must be no unauthorised connection upstream of the meter; the supply/transporter owns the assets up to and including the ECV/meter as applicable.",
      ],
      refs: ["GSIUR 1998", "IGEM/GM standards", "Gas emergency notice requirement"],
      watch: "The ECV must be accessible and operable by the consumer — a buried, seized or obstructed ECV is a real safety defect.",
    },
    {
      id: "meter-bonding",
      cat: "met1",
      title: "Meter position, bonding & MET",
      summary: "Equipotential bonding at the meter and where it must be located.",
      points: [
        "Main equipotential bonding connects the gas installation pipework to the Main Earthing Terminal (MET) to keep exposed metalwork at the same potential under fault conditions.",
        "The bonding conductor is a minimum of 10 mm² for domestic main bonding and clamps to the consumer's pipework.",
        "The bonding clamp must be fitted to the consumer side, within 600 mm of the meter outlet/ECV, and before any branch, tee or appliance.",
        "Meters must be positioned to allow access for reading, maintenance and emergency isolation, and protected from heat, damp and damage.",
        "External meter boxes protect the meter and must be weatherproof with the key/access available to the consumer.",
        "Check the bond is present, correctly sized, correctly placed and in good condition as part of the work.",
      ],
      refs: ["BS 7671 (bonding)", "GSIUR 1998", "IGEM/GM standards"],
      watch: "Bond placement matters: 10 mm² minimum, within 600 mm of the meter on the consumer side, before any tee/branch. Wrong size or position is a defect.",
    },
  ];

  // ---- Flashcards ----------------------------------------------------
  // Quick recall: { cat, q, a }
  const flashcards = [
    { cat: "ccn1", q: "What is the National Gas Emergency Service phone number?", a: "0800 111 999 — free, 24 hours, for reporting gas escapes/emergencies." },
    { cat: "ccn1", q: "Which regulations are the principal law for gas installation and use?", a: "Gas Safety (Installation and Use) Regulations 1998 (GSIUR)." },
    { cat: "ccn1", q: "When did the Gas Safe Register replace CORGI?", a: "1 April 2009." },
    { cat: "ccn1", q: "What are the three GIUSP classifications?", a: "Immediately Dangerous (ID), At Risk (AR), and Not to Current Standards (NCS). Note: under current IGEM/G/11 Edition 2, only ID and AR are 'unsafe situations' — NCS is recorded/advised but not put on a Warning Notice." },
    { cat: "ccn1", q: "Under IGEM/G/11 Edition 2, how many categories of UNSAFE situation are there, and what are they?", a: "Two — Immediately Dangerous (ID) and At Risk (AR). NCS is no longer a GIUSP unsafe category." },
    { cat: "ccn1", q: "Name an 'At Risk' situation where turning the gas off does NOT make it safer.", a: "E.g. building work over a PE gas service pipe, or an incorrectly sited LPG bulk vessel — refer to a responsible person/organisation; these don't get a 'DANGER — DO NOT USE' label." },
    { cat: "ccn1", q: "What is the nominal natural gas appliance operating pressure?", a: "20 mbar (check against the appliance data badge)." },
    { cat: "ccn1", q: "Maximum permitted pressure drop across installation pipework (meter to appliance), natural gas?", a: "1 mbar." },
    { cat: "ccn1", q: "What is the maximum acceptable CO/CO₂ ratio for a correctly operating appliance?", a: "0.004 — above this it fails on combustion." },
    { cat: "ccn1", q: "Open-flued ventilation rule of thumb?", a: "5 cm² of free air per kW of net input ABOVE 7 kW (BS 5440-2)." },
    { cat: "ccn1", q: "Which standard covers domestic installation pipework up to 35 mm?", a: "BS 6891." },
    { cat: "ccn1", q: "Which standard covers domestic flueing; which covers ventilation?", a: "BS 5440-1 (flues) and BS 5440-2 (ventilation)." },
    { cat: "ccn1", q: "On NEW installation pipework, how much pressure drop is allowed on the tightness test?", a: "None — no pressure drop is permitted." },
    { cat: "ccn1", q: "Which standard covers domestic tightness testing & purging?", a: "IGEM/UP/1B — current is Edition 4 (mandatory from 1 October 2026; Edition 3 withdrawn 30 September 2026)." },
    { cat: "ccn1", q: "What is the key change in IGEM/UP/1B Edition 4?", a: "The permissible pressure drop is set by Installation Volume (IV in m³), not the meter's badged size. (IGEM/UP/1B covers up to IV 0.035 m³.)" },
    { cat: "ccn1", q: "New procedural step in IGEM/UP/1B Edition 4 when appliances are connected?", a: "A pipework-only retest is now a mandatory follow-on step — any perceptible movement on it is a fail." },
    { cat: "ccn1", q: "Order of the two flue checks on an open-flued appliance?", a: "Flue flow (smoke) test first, then the spillage test." },
    { cat: "ccn1", q: "Early symptoms of carbon monoxide poisoning?", a: "Headache, dizziness, nausea, tiredness, breathlessness — flu-like but no temperature; eases when away from the property." },
    { cat: "ccn1", q: "Which standard do CO alarms conform to?", a: "BS EN 50291 (siting guidance in BS EN 50292)." },
    { cat: "ccn1", q: "Metric gas-rate formula?", a: "Gas rate (m³/h) = (3600 ÷ time in seconds) × volume used (m³)." },
    { cat: "ccn1", q: "Why use the calorific value from the gas bill, not a textbook figure?", a: "CV varies; using the wrong value gives an incorrect kW heat input." },
    { cat: "ccn1", q: "Minimum main equipotential bonding conductor size (domestic)?", a: "10 mm²." },
    { cat: "cenwat", q: "Three main domestic boiler types?", a: "Combi, system, and regular (heat-only)." },
    { cat: "cenwat", q: "Typical pressure relief (safety) valve setting on a sealed system?", a: "3 bar." },
    { cat: "cenwat", q: "Typical cold-fill pressure of a sealed heating system?", a: "Around 1–1.5 bar." },
    { cat: "cenwat", q: "What does an expansion vessel do?", a: "Absorbs the expansion of water as it heats so system pressure stays within limits." },
    { cat: "cenwat", q: "Boiler Plus: what extra measure must a combi have (England, 2018)?", a: "One of: flue gas heat recovery, weather compensation, load compensation, or a smart thermostat with automation & optimisation." },
    { cat: "cenwat", q: "Minimum gas boiler efficiency under Boiler Plus?", a: "ErP 92%." },
    { cat: "cenwat", q: "Do you need CENWAT alone to install an unvented cylinder?", a: "No — unvented hot water needs the separate G3/unvented qualification." },
    { cat: "cenwat", q: "Recommended stored hot water temperature (Legionella control)?", a: "60 °C stored, distributed generally ≥ 50 °C, balancing scald risk." },
    { cat: "cenwat", q: "Common winter cause of a condensing boiler lockout?", a: "A frozen external condensate pipe." },
    { cat: "ckr1", q: "What must a freestanding cooker have to prevent tipping?", a: "A stability device (chain/bracket) per BS 6172." },
    { cat: "ckr1", q: "Which standard covers flexible connection hoses for domestic cookers?", a: "BS 669-1." },
    { cat: "ckr1", q: "What type of appliance is a gas cooker (flue-wise)?", a: "Flueless — products enter the room, so room volume and ventilation matter." },
    { cat: "ckr1", q: "Cooker ventilation: roughly what vent for a room under 5 m³?", a: "About 100 cm² permanent vent (verify against current BS 5440-2)." },
    { cat: "htr1", q: "What does DFE stand for, and what flue does it need?", a: "Decorative Fuel Effect fire — needs a suitable Class 1/large chimney with good draught." },
    { cat: "htr1", q: "What two fabric features are often required for an open-flued fire in a builder's opening?", a: "A sealed closure (register/debris) plate and a catchment (debris collection) space." },
    { cat: "htr1", q: "What safety device do flueless heaters/fires use?", a: "An atmosphere-sensing / oxygen-depletion device that shuts the appliance off if oxygen is depleted." },
    { cat: "htr1", q: "Which standard covers installation of gas fires/space heaters?", a: "BS 5871." },
    { cat: "met1", q: "What is the ECV and what's its role?", a: "Emergency Control Valve — the consumer's main means of shutting off the gas; must be accessible and clearly identifiable." },
    { cat: "met1", q: "What must be displayed at/near the meter?", a: "A gas emergency notice telling the user what to do if they smell gas (incl. 0800 111 999)." },
    { cat: "met1", q: "Where must the main bonding clamp be fitted?", a: "Consumer side, within 600 mm of the meter outlet/ECV, before any branch, tee or union." },
    { cat: "met1", q: "What is the MET?", a: "Main Earthing Terminal — the point the gas installation pipework is bonded to for equipotential bonding." },
  ];

  // ---- Quiz questions ------------------------------------------------
  // { cat, q, options:[...], answer:index, explain }
  const quiz = [
    { cat: "ccn1", q: "What is the maximum permitted pressure drop across domestic installation pipework (meter to appliance) on natural gas?",
      options: ["0.5 mbar", "1 mbar", "2.5 mbar", "5 mbar"], answer: 1,
      explain: "The maximum permitted drop from the meter outlet to the appliance is 1 mbar for natural gas (BS 6891)." },
    { cat: "ccn1", q: "The accepted maximum CO/CO₂ ratio for a correctly operating appliance is:",
      options: ["0.0004", "0.004", "0.04", "0.4"], answer: 1,
      explain: "A ratio above 0.004 is a combustion failure — investigate ventilation, flue and gas rate." },
    { cat: "ccn1", q: "Which standard covers domestic ventilation requirements for gas appliances?",
      options: ["BS 5440-1", "BS 5440-2", "BS 6891", "BS 6172"], answer: 1,
      explain: "BS 5440-2 = ventilation; BS 5440-1 = flueing." },
    { cat: "ccn1", q: "For an open-flued appliance, the rule of thumb for ventilation free area is:",
      options: ["5 cm² per kW of total input", "5 cm² per kW of net input above 7 kW", "10 cm² per kW above 5 kW", "No ventilation needed"], answer: 1,
      explain: "It's 5 cm² of free air per kW of net input ABOVE the first 7 kW (BS 5440-2)." },
    { cat: "ccn1", q: "On NEW installation pipework with no appliances connected, the permitted pressure drop on a tightness test is:",
      options: ["1 mbar", "4 mbar", "8 mbar", "Zero — no drop permitted"], answer: 3,
      explain: "New pipework must hold with no pressure drop. A permitted drop only applies to existing installations with appliances (read from the IGEM/UP/1B tables)." },
    { cat: "ccn1", q: "Under IGEM/UP/1B Edition 4, the permissible tightness-test pressure drop is determined by:",
      options: ["The meter's badged size", "The Installation Volume (IV) in m³", "The number of appliances", "A fixed 4 mbar"], answer: 1,
      explain: "Edition 4 (mandatory 1 Oct 2026) sets the permitted drop by Installation Volume — the actual internal gas volume of the section under test — not the meter size. It also makes a pipework-only retest mandatory when appliances are connected." },
    { cat: "ccn1", q: "Which of these is the correct order of tests on an open-flued appliance?",
      options: ["Spillage test then flue flow test", "Flue flow test then spillage test", "Only a spillage test is needed", "Only a flue flow test is needed"], answer: 1,
      explain: "Flue flow (smoke) test proves the flue is clear/pulling; then the spillage test confirms products are removed in worst-case conditions." },
    { cat: "ccn1", q: "Which body maintains the register that gas operatives must be on to work legally?",
      options: ["CORGI", "HSE", "Gas Safe Register", "OFGEM"], answer: 2,
      explain: "Gas Safe Register replaced CORGI on 1 April 2009; HSE is the enforcing authority." },
    { cat: "ccn1", q: "An appliance is an immediate danger to life if left connected. Under GIUSP this is classed as:",
      options: ["Not to Current Standards (NCS)", "At Risk (AR)", "Immediately Dangerous (ID)", "Acceptable"], answer: 2,
      explain: "Immediately Dangerous — make safe with permission (turn off/disconnect, cap, label, advise)." },
    { cat: "ccn1", q: "The nominal operating pressure for a natural gas appliance is:",
      options: ["10 mbar", "20 mbar", "37 mbar", "50 mbar"], answer: 1,
      explain: "Natural gas nominal working pressure is 20 mbar (37 mbar is propane). Always check the data badge." },
    { cat: "ccn1", q: "Carbon monoxide is best described as:",
      options: ["A pungent-smelling gas", "Colourless, odourless and toxic", "Heavier than air with a sweet smell", "Visible as a blue haze"], answer: 1,
      explain: "CO cannot be detected by the senses — colourless, odourless, tasteless and toxic." },
    { cat: "cenwat", q: "The pressure relief (safety) valve on a sealed heating system is typically set to:",
      options: ["1 bar", "1.5 bar", "3 bar", "6 bar"], answer: 2,
      explain: "PRV is usually set to 3 bar and must discharge to a safe, visible point outside." },
    { cat: "cenwat", q: "Under Boiler Plus (England), a new combi installation must include one of:",
      options: ["A larger radiator", "Flue gas heat recovery, weather comp, load comp, or a smart thermostat", "A magnetic filter only", "A power flush"], answer: 1,
      explain: "Combis need one additional energy-saving measure on top of time & temperature control." },
    { cat: "cenwat", q: "To install/commission an unvented hot water cylinder you must hold:",
      options: ["Only CENWAT", "Only CCN1", "The separate G3/unvented qualification", "No extra qualification"], answer: 2,
      explain: "Unvented hot water needs the dedicated G3 competence — it isn't covered by CENWAT alone." },
    { cat: "cenwat", q: "A common winter cause of a condensing boiler going to lockout is:",
      options: ["Low room temperature", "A frozen external condensate pipe", "Too much ventilation", "High mains pressure"], answer: 1,
      explain: "External condensate pipes freeze — insulate, upsize and keep them short, or route internally." },
    { cat: "cenwat", q: "Recommended stored hot water temperature for Legionella control is around:",
      options: ["40 °C", "50 °C", "60 °C", "80 °C"], answer: 2,
      explain: "Store at 60 °C and distribute generally ≥ 50 °C, while managing scald risk." },
    { cat: "ckr1", q: "A freestanding gas cooker must be fitted with:",
      options: ["A flue", "A stability device (chain/bracket)", "An air vent of 100 cm²", "A pressure relief valve"], answer: 1,
      explain: "A stability bracket/chain (BS 6172) stops the cooker tipping when weight is applied to an open door." },
    { cat: "ckr1", q: "Flexible connection hoses for domestic cookers should comply with:",
      options: ["BS 6891", "BS 669-1", "BS 5440-1", "BS 7671"], answer: 1,
      explain: "BS 669-1 covers domestic cooker flexible hoses." },
    { cat: "ckr1", q: "A gas cooker is what type of appliance with respect to its combustion products?",
      options: ["Room-sealed", "Open-flued", "Flueless", "Fan-flued"], answer: 2,
      explain: "Cookers are flueless — products enter the room, so room volume/ventilation and an openable window matter." },
    { cat: "htr1", q: "A DFE (Decorative Fuel Effect) fire requires:",
      options: ["No flue", "A suitable large/Class 1 chimney with good draught", "A balanced flue only", "A condensate drain"], answer: 1,
      explain: "DFE fires need a proper chimney and good draught; an inadequate flue causes spillage and CO risk." },
    { cat: "htr1", q: "Which feature collects debris falling from a chimney above an open-flued fire?",
      options: ["A closure plate", "A catchment space", "A tundish", "An expansion vessel"], answer: 1,
      explain: "A catchment (debris collection) space sits below the flue connection; a sealed closure/register plate is also commonly required." },
    { cat: "htr1", q: "Flueless heaters incorporate which safety device?",
      options: ["A pressure relief valve", "An oxygen-depletion / atmosphere-sensing device", "A flame supervision pilot only", "A condensate trap"], answer: 1,
      explain: "An atmosphere-sensing device shuts the heater off if oxygen in the room becomes depleted." },
    { cat: "met1", q: "The consumer's main means of shutting off the gas supply is the:",
      options: ["Meter regulator", "Emergency Control Valve (ECV)", "Service valve", "Appliance isolation valve"], answer: 1,
      explain: "The ECV must be accessible and clearly identifiable, with a notice telling users what to do if they smell gas." },
    { cat: "met1", q: "The main equipotential bonding clamp must be fitted:",
      options: ["Anywhere on the pipework", "On the supply side of the meter", "Within 600 mm of the meter outlet, consumer side, before any branch", "At the furthest appliance"], answer: 2,
      explain: "10 mm² minimum, consumer side, within 600 mm of the meter/ECV, before any tee/branch/union." },
    { cat: "met1", q: "What must be displayed at or near the gas meter?",
      options: ["The boiler instructions", "A gas emergency notice", "The landlord's name", "The last service date"], answer: 1,
      explain: "A gas emergency notice tells the user what to do if they smell gas, including the 0800 111 999 number." },
  ];

  return { categories, topics, flashcards, quiz };
})();
